'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



''' <summary>
''' LoginPage class.
''' </summary>
''' <remarks>
''' Auto-generated class.
''' </remarks>

Imports Microsoft.VisualBasic
Imports System
Partial Public Class LoginPage

	''' <summary>
	''' Head1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

	''' <summary>
	''' ProgressControl control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ProgressControl As Global.DevExpress.ExpressApp.Web.Controls.ProgressControl

	''' <summary>
	''' ViewCaption control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ViewCaption As Global.System.Web.UI.WebControls.Literal

	''' <summary>
	''' form1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	''' <summary>
	''' ErrorInfo control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ErrorInfo As Global.DevExpress.ExpressApp.Web.Templates.Controls.ErrorInfoControl

	''' <summary>
	''' ViewSite control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ViewSite As Global.System.Web.UI.WebControls.PlaceHolder

	''' <summary>
	''' PopupActions control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected PopupActions As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer
End Class
